project:
  type: website
  output-dir: docs

website:
  title: "F&L"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pages/page1.qmd
        text: Page 1
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

