project:
  type: website
  output-dir: docs

website:
  title: "F&L"
  navbar:
    left:
      - href: pages/page1.qmd
        text: Pré-traitements
      - href: pages/page2.qmd
        text: Fruits & Légumes
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

